### ISSUE TITLE
Correct signature used with/for awful.tag.attached_connect_signal?

### ISSUE THREAD

**Issue by blueyed** [guotsuan/eminent#3]
From https://github.com/guotsuan/eminent/blame/master/eminent.lua#L141-L147:

    awful.tag.attached_connect_signal(screen, "property::selected", ut)

`ut` is defined as:

    local function ut(s,t) gettags(s.index) end

However, it appears that the first argument passed by awful/awesome is a tag, and not a screen:

    local function attached_connect_signal_screen(screen, sig, func)
        capi.tag.connect_signal(sig, function(_tag, ...)
            if tag.getscreen(_tag) == screen then
                func(_tag)
            end
        end)
    end

Shouldn't `ut` look like this?

    local function ut(t) autohidetags(awful.tag.getscreen(t)) end

I might be missing something here, of course.

**Comment by guotsuan** [comment]
Now all the signal related functions has been removed from eminent. I think it is not necessary for eminent to handle them.
