### ISSUE TITLE
Problems with current implementation

### ISSUE THREAD

**Issue by Xiaoming94** [guotsuan/eminent#4]
Hello, with the current implementation. This plugin loses it's purpose since now it only hides tags with no clients.
 
To put this in context: If you have a 14 index long array of tags, You do wrap ALL THE WAY to the left most, and right most index. Which means, basiclly, that when you want to go left from the first index in your array taglist, you Wrap around all the way to index 14, and than you have to walk all the way to the first tag with a client. For example, If you have a active client on tag 4 and no active window on tag 5, you are on tag 1, Before when you goes left, you just get to tag 4 (since, that is where you have a window), Now, you goes all the way to 14 and have to go from their to tag 4 yourself.

Like wise, with the old implementation, when at you rightmost empty tag, when going right, you want to wrap-around to tag 1 again, but now, you just continues walking through your taglist.

**Comment by guotsuan** [comment]
Hi,

I got your points. Now the codes have been updated. Please checkout the new version. I think it should work as before.

**Comment by Xiaoming94** [comment]
It works like a charm! A bit strange though is that you need the git version of Awesome in Archlinux for this to work

**Comment by guotsuan** [comment]
I'm using the git version of Awesome in archlinux. But it is strange that it only works with the git version of Awesome. Do you get any errors if you use it with stable version of awesome? I cannot test it now. But I will test it again with the stable version, when I'm home.

**Comment by guotsuan** [comment]
I have found the reason why the current codes only works for git version. The function, awful.screen.focused() is a new function that is only available in git version. I have updated the codes. 
Now it should work with the stable version too.

**Comment by Xiaoming94** [comment]
Works like a charm! Thank you! :D

**Comment by guotsuan** [comment]
You are welcome. :D And thanks for spotting the problem.
